port=53
bind-dynamic
except-interface=lo

server=/youtube.com/8.8.8.8
server=/google.com/8.8.8.8
server=/goo.gl/8.8.8.8
server=/facebook.com/8.8.8.8
server=/instagram.com/8.8.8.8
server=/cdninstagram.com/8.8.8.8

server=8.8.8.8

cache-size=1000
